###DATA SETTINGS
# Directory containing training data
data_dir: "../data/training"

# Directory containing validation data
data_dir_val: "../data/validation"

# Which slices to include (e.g., "all", "middle", etc.)
type_slices: "all"

# Whether to include noised verions of the images
noised: true

# Image size (assumed square)
image_size: 256

# Use a single contrast MRI sequence (T2 FLAIR in our case)
single_contrast: false

###### MODEL PARAMS
# Depth of the regressor model
regressor_depth: 4

# Width (channels) of the regressor model
regressor_width: 32

# Attention resolutions used in the regressor
regressor_attention_resolutions: "32,16,8"

# Type of pooling used in the regressor
regressor_pool: "attention"

# Whether to use resblock up/down sampling
regressor_resblock_updown: true

# Whether to use scale-shift normalization
regressor_use_scale_shift_norm: true


#### TRIANING SETTINGS
# Total number of training iterations
iterations: 50000 

# Learning rate
lr: !!float 1e-4

# Batch size
batch_size: 3

# How often (in steps) to log training info
log_interval: 1

# How often (in steps) to evaluate model
eval_interval: 1000

# How often (in steps) to save model
save_interval: 1000

# Dataset name
dataset: "brats"

# Whether this is a regression task
regression: true


### OUTPUT SETTINGS
# Where to save results
results_dir: "./results"


#####OTHERS
# Path to resume checkpoint from
resume_checkpoint: ""


# Device to use ('cpu', 'cuda', or custom like 'cluster')
device: "cluster"