###DATA SETTINGS
# Directory containing data
data_dir: "./data/testing"

# Which slices to include (e.g., "all", "middle", etc.)
type_slices: "all"

# Whether to include noised verions of the images
noised: true

# Image size (assumed square)
image_size: 256

# Dataset name
dataset: "brats"

# Whether this is a regression task
regression: true

# Whether to use single contrast MRI
single_contrast: false


###### MODEL PARAMS
# Path of the regressor
regressor_path: './results_traing/model050000.pt'

# Depth of the regressor model
regressor_depth: 4

# Width (channels) of the regressor model
regressor_width: 32

# Attention resolutions used in the regressor
regressor_attention_resolutions: "32,16,8"

# Type of pooling used in the regressor
regressor_pool: "attention"

# Whether to use resblock up/down sampling
regressor_resblock_updown: true

# Whether to use scale-shift normalization
regressor_use_scale_shift_norm: true


### OUTPUT SETTINGS
# Where to save results (path, must end with .csv)
saving_name : "./results/test.csv"

# Whether to save individual results
save_details: true


#####OTHERS
# Whether to use single contrast MRI
single_contrast: false

# Device to use ('cpu', 'cuda', or custom like 'cluster')
device: "cluster"