### DATA SETTINGS
# Directory containing training data
data_dir_train: "../data/training"

# Directory containing validation data
data_dir_val: "../data/validation"

# Dataset name
dataset: "brats"

# Image size (height and width)
image_size: 256

# Use a single contrast MRI sequence (T2 FLAIR in our case)
single_contrast: false

### MODEL PARAMS - must be same as the trained model
# Model path - full path where the model being tested is stored
model_path: './results_traing/model050000.pt'

# Number of base channels in the model
num_channels: 128

# Number of residual blocks per resolution
num_res_blocks: 2

# Number of attention heads
num_heads: 1

# Enable class conditioning
class_cond: true

# Learn the noise level (sigma)
learn_sigma: true

# Use scale and shift in normalization
use_scale_shift_norm: false

# Resolutions at which attention is applied
attention_resolutions: '16'

### DIFFUSION PROCESS SETTINGS
# Number of diffusion steps
diffusion_steps: 1000

# Noise schedule to use
noise_schedule: "linear"

# Rescale learned sigmas
rescale_learned_sigmas: false

# Rescale diffusion timesteps
rescale_timesteps: false



### TRAINING SETTINGS
# Learning rate
lr: !!float 1e-4

# Batch size
batch_size: 10

# Interval (in steps) to save model checkpoints
save_interval: 5000


### OUTPUT SETTINGS
# Directory where results (checkpoints, samples, etc.) will be saved
results_dir: "./results"


#####OTHERS
# Path to resume training from a checkpoint
resume_checkpoint: ""

